### ISSUE TITLE
Providing API interface so others can implement custom widgets

### ISSUE THREAD

**Issue by SirWindfield** [Ashley1227/mctouchbar-fabric#1]
What about if we provide an interface that others could use to create custom widgets? The build-in ones could then be converted to implement that interface. Your mod would then take all registered implementations and offer the user the choice to choose from them:

```java
public interface WidgetCreator {
    Widget createWidget();
}
```

```java
public static class MBTouchbarAPI {
	private static final List<WidgetCreator> creators = new ArrayList<>();

	public static void registerWidgetCreator(WidgetCreator creator) {
		if (creator != null) {
			this.creators.add(creator);
  		}
    }
}
```

Just the idea behind it. Mods could then create new type of widgets without modifying this library. Just an example, Botania could add a widget to open the lexicon that could be included in their mod instead of this one.

Brainstorming is probably required to how to design this but I wanted to throw the idea in

**Comment by Ashley1227** [comment]
uhh yeah. I'm  kinda like in a depressive funk right now so uh if you want to add that? Idk. Probably will do it later but yeah.

**Comment by SirWindfield** [comment]
Sure I can implement this. I’ll take a look as well on how to avoid crashes on other OS than macOS. Do you prefer a PR or me pushing into this repo on another branch ?

**Comment by Ashley1227** [comment]
PR is probably better. Thanks.
