### ISSUE TITLE
Please update for 1.15.2

### ISSUE THREAD

**Issue by systemm0** [Ashley1227/mctouchbar-fabric#3]
I would really love to be able to use this on 1.15.2

maybe even better would be information on how to update this ourselves in the future. I really want to try this mod, but when loading 1.15.2 it goes into a loop of "saving world" over and over.

**Comment by Ashley1227** [comment]
I'm currently working on that :)

**Comment by systemm0** [comment]
you dah bomb!

**Comment by Ashley1227** [comment]
Done C:

Btw...are you interested in helping at all? I could use some help with translations and with putting this on Maven Central.

**Comment by systemm0** [comment]
I only know english unfortunately. I am also not a programmer. I am willing to test however. pm on discord or you will find me on the NA AOF2 server.

**Comment by Ashley1227** [comment]
Alright C:

that's fine. If you have any issues or suggestions you can [PM me on Discord](Ashley1227.github.io/discord) or post here. Thanks!
